# Generated by Django 5.1.6 on 2025-02-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_caipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_admin', models.TextField()),
                ('name_admin', models.TextField()),
                ('lastna_admin', models.TextField()),
                ('age_admin', models.TextField(blank=True)),
                ('phone_admin', models.TextField()),
                ('email_admin', models.TextField()),
                ('direcc_admin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.TextField()),
                ('informe_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='direc_caipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_direc', models.TextField()),
                ('name_direc', models.TextField()),
                ('lastna_direc', models.TextField()),
                ('phone_direc', models.TextField()),
                ('email_direc', models.TextField()),
                ('direcc_direc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_loggin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced', models.TextField()),
                ('email', models.TextField()),
                ('rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='areaestudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caipa.areas')),
            ],
        ),
        migrations.CreateModel(
            name='student_caipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_stu', models.TextField()),
                ('name_stu', models.TextField()),
                ('lastna_stu', models.TextField()),
                ('age_stu', models.TextField()),
                ('direcc_stu', models.TextField()),
                ('fech_nac', models.DateTimeField(blank=True, null=True)),
                ('cami_stu', models.TextField(blank=True)),
                ('pan_stu', models.TextField(blank=True)),
                ('zapa_stu', models.TextField(blank=True)),
                ('birth_stu', models.TextField(blank=True)),
                ('state_stu', models.TextField(blank=True)),
                ('natio_stu', models.TextField(blank=True)),
                ('country_stu', models.TextField(blank=True)),
                ('gender', models.TextField(blank=True)),
                ('pes_stu', models.TextField(blank=True)),
                ('grp_sng_stu', models.TextField(blank=True)),
                ('email_stu', models.TextField(blank=True)),
                ('area', models.ManyToManyField(through='caipa.areaestudiante', to='caipa.areas')),
            ],
        ),
        migrations.CreateModel(
            name='repre_caipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_repre', models.TextField()),
                ('name_repre', models.TextField()),
                ('lastna_repre', models.TextField()),
                ('age_repre', models.TextField(blank=True)),
                ('number_repre', models.TextField(blank=True)),
                ('phone_repre', models.TextField()),
                ('email_repre', models.TextField()),
                ('direcc_repre', models.TextField()),
                ('id_estu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caipa.student_caipa')),
            ],
        ),
        migrations.AddField(
            model_name='areaestudiante',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caipa.student_caipa'),
        ),
        migrations.CreateModel(
            name='teacher_caipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_tea', models.TextField()),
                ('name_tea', models.TextField()),
                ('lastna_tea', models.TextField()),
                ('age_tea', models.TextField(blank=True)),
                ('phone_tea', models.TextField()),
                ('email_tea', models.TextField()),
                ('direcc_tea', models.TextField()),
                ('area', models.ManyToManyField(through='caipa.areaestudiante', to='caipa.areas')),
                ('id_estu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caipa.student_caipa')),
            ],
        ),
        migrations.AddField(
            model_name='areaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caipa.teacher_caipa'),
        ),
    ]
